"""rename_omdb

Revision ID: 03221cef9427
Revises: 
Create Date: 2026-07-24 02:25:32.179744

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03221cef9427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('omdb_id', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_media_status_tmdb'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_tmdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_file_unique_id'), table_name='media_items')
    op.create_index(op.f('ix_media_items_file_unique_id'), 'media_items', ['file_unique_id'], unique=False)
    op.create_index('idx_media_status_omdb', 'media_items', ['status', 'omdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_omdb_id'), 'media_items', ['omdb_id'], unique=False)
    op.drop_column('media_items', 'tmdb_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_media_items_omdb_id'), table_name='media_items')
    op.drop_index('idx_media_status_omdb', table_name='media_items')
    op.drop_index(op.f('ix_media_items_file_unique_id'), table_name='media_items')
    op.create_index(op.f('ix_media_items_file_unique_id'), 'media_items', ['file_unique_id'], unique=True)
    op.create_index(op.f('ix_media_items_tmdb_id'), 'media_items', ['tmdb_id'], unique=False)
    op.create_index(op.f('idx_media_status_tmdb'), 'media_items', ['status', 'tmdb_id'], unique=False)
    op.drop_column('media_items', 'omdb_id')
    # ### end Alembic commands ###
