"""add_batch_links

Revision ID: 6c2ab6090bcd
Revises: 03221cef9427
Create Date: 2026-07-24 02:49:35.719564

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2ab6090bcd'
down_revision: Union[str, None] = '03221cef9427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_links',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('item_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_links')
    # ### end Alembic commands ###
